// PokeForge — canonical reference data for pokeemerald-expansion
// Source: rh-hideout/pokeemerald-expansion (verified against the PDF guide)

// ---------------------------------------------------------------------------
// Elemental types (Gen 1-9) — order matches expansion's TYPE_* enum
// ---------------------------------------------------------------------------
export const POKEMON_TYPES: { constant: string; name: string; color: string }[] = [
  { constant: "TYPE_NORMAL", name: "Normal", color: "#A8A77A" },
  { constant: "TYPE_FIGHTING", name: "Fighting", color: "#C22E28" },
  { constant: "TYPE_FLYING", name: "Flying", color: "#A98FF3" },
  { constant: "TYPE_POISON", name: "Poison", color: "#A33EA1" },
  { constant: "TYPE_GROUND", name: "Ground", color: "#E2BF65" },
  { constant: "TYPE_ROCK", name: "Rock", color: "#B6A136" },
  { constant: "TYPE_BUG", name: "Bug", color: "#A6B91A" },
  { constant: "TYPE_GHOST", name: "Ghost", color: "#735797" },
  { constant: "TYPE_STEEL", name: "Steel", color: "#B7B7CE" },
  { constant: "TYPE_FIRE", name: "Fire", color: "#EE8130" },
  { constant: "TYPE_WATER", name: "Water", color: "#6390F0" },
  { constant: "TYPE_GRASS", name: "Grass", color: "#7AC74C" },
  { constant: "TYPE_ELECTRIC", name: "Electric", color: "#F7D02C" },
  { constant: "TYPE_PSYCHIC", name: "Psychic", color: "#F95587" },
  { constant: "TYPE_ICE", name: "Ice", color: "#96D9D6" },
  { constant: "TYPE_DRAGON", name: "Dragon", color: "#6F35FC" },
  { constant: "TYPE_DARK", name: "Dark", color: "#705746" },
  { constant: "TYPE_FAIRY", name: "Fairy", color: "#D685AD" },
  { constant: "TYPE_STELLAR", name: "Stellar", color: "#406580" },
  { constant: "TYPE_MYSTERY", name: "???", color: "#68A090" },
];

export const TYPE_NAME = (constant: string) =>
  POKEMON_TYPES.find((t) => t.constant === constant)?.name ?? constant.replace("TYPE_", "");

export const TYPE_COLOR = (constant: string) =>
  POKEMON_TYPES.find((t) => t.constant === constant)?.color ?? "#68A090";

// ---------------------------------------------------------------------------
// Growth rates
// ---------------------------------------------------------------------------
export const GROWTH_RATES = [
  "GROWTH_MEDIUM_FAST",
  "GROWTH_ERRATIC",
  "GROWTH_FLUCTUATING",
  "GROWTH_MEDIUM_SLOW",
  "GROWTH_SLOW",
  "GROWTH_FAST",
];

// ---------------------------------------------------------------------------
// Egg groups
// ---------------------------------------------------------------------------
export const EGG_GROUPS = [
  "EGG_GROUP_NONE",
  "EGG_GROUP_MONSTER",
  "EGG_GROUP_WATER_1",
  "EGG_GROUP_BUG",
  "EGG_GROUP_FLYING",
  "EGG_GROUP_FIELD",
  "EGG_GROUP_FAIRY",
  "EGG_GROUP_GRASS",
  "EGG_GROUP_HUMAN_LIKE",
  "EGG_GROUP_WATER_3",
  "EGG_GROUP_MINERAL",
  "EGG_GROUP_AMORPHOUS",
  "EGG_GROUP_WATER_2",
  "EGG_GROUP_DITTO",
  "EGG_GROUP_DRAGON",
  "EGG_GROUP_NO_EGGS_DISCOVERABLE",
];

// ---------------------------------------------------------------------------
// Body colors
// ---------------------------------------------------------------------------
export const BODY_COLORS = [
  "BODY_COLOR_RED",
  "BODY_COLOR_BLUE",
  "BODY_COLOR_YELLOW",
  "BODY_COLOR_GREEN",
  "BODY_COLOR_BLACK",
  "BODY_COLOR_BROWN",
  "BODY_COLOR_PURPLE",
  "BODY_COLOR_GRAY",
  "BODY_COLOR_WHITE",
  "BODY_COLOR_PINK",
];

// ---------------------------------------------------------------------------
// Built-in abilities (subset — custom ones are added per-project)
// ---------------------------------------------------------------------------
export const BUILTIN_ABILITIES: { constant: string; name: string }[] = [
  { constant: "ABILITY_NONE", name: "None" },
  { constant: "ABILITY_STENCH", name: "Stench" },
  { constant: "ABILITY_DRIZZLE", name: "Drizzle" },
  { constant: "ABILITY_SPEED_BOOST", name: "Speed Boost" },
  { constant: "ABILITY_BATTLE_ARMOR", name: "Battle Armor" },
  { constant: "ABILITY_STURDY", name: "Sturdy" },
  { constant: "ABILITY_DAMP", name: "Damp" },
  { constant: "ABILITY_LIMBER", name: "Limber" },
  { constant: "ABILITY_SAND_VEIL", name: "Sand Veil" },
  { constant: "ABILITY_STATIC", name: "Static" },
  { constant: "ABILITY_VOLT_ABSORB", name: "Volt Absorb" },
  { constant: "ABILITY_WATER_ABSORB", name: "Water Absorb" },
  { constant: "ABILITY_OBLIVIOUS", name: "Oblivious" },
  { constant: "ABILITY_CLOUD_NINE", name: "Cloud Nine" },
  { constant: "ABILITY_COMPOUND_EYES", name: "Compound Eyes" },
  { constant: "ABILITY_INSOMNIA", name: "Insomnia" },
  { constant: "ABILITY_COLOR_CHANGE", name: "Color Change" },
  { constant: "ABILITY_IMMUNITY", name: "Immunity" },
  { constant: "ABILITY_FLASH_FIRE", name: "Flash Fire" },
  { constant: "ABILITY_SHIELD_DUST", name: "Shield Dust" },
  { constant: "ABILITY_OWN_TEMPO", name: "Own Tempo" },
  { constant: "ABILITY_SUCTION_CUPS", name: "Suction Cups" },
  { constant: "ABILITY_INTIMIDATE", name: "Intimidate" },
  { constant: "ABILITY_SHADOW_TAG", name: "Shadow Tag" },
  { constant: "ABILITY_ROUGH_SKIN", name: "Rough Skin" },
  { constant: "ABILITY_WONDER_GUARD", name: "Wonder Guard" },
  { constant: "ABILITY_LEVITATE", name: "Levitate" },
  { constant: "ABILITY_EFFECT_SPORE", name: "Effect Spore" },
  { constant: "ABILITY_SYNCHRONIZE", name: "Synchronize" },
  { constant: "ABILITY_CLEAR_BODY", name: "Clear Body" },
  { constant: "ABILITY_NATURAL_CURE", name: "Natural Cure" },
  { constant: "ABILITY_LIGHTNING_ROD", name: "Lightning Rod" },
  { constant: "ABILITY_SERENE_GRACE", name: "Serene Grace" },
  { constant: "ABILITY_SWIFT_SWIM", name: "Swift Swim" },
  { constant: "ABILITY_CHLOROPHYLL", name: "Chlorophyll" },
  { constant: "ABILITY_ILLUMINATE", name: "Illuminate" },
  { constant: "ABILITY_TRACE", name: "Trace" },
  { constant: "ABILITY_HUGE_POWER", name: "Huge Power" },
  { constant: "ABILITY_POISON_POINT", name: "Poison Point" },
  { constant: "ABILITY_INNER_FOCUS", name: "Inner Focus" },
  { constant: "ABILITY_MAGMA_ARMOR", name: "Magma Armor" },
  { constant: "ABILITY_WATER_VEIL", name: "Water Veil" },
  { constant: "ABILITY_MAGNET_PULL", name: "Magnet Pull" },
  { constant: "ABILITY_SOUNDPROOF", name: "Soundproof" },
  { constant: "ABILITY_RAIN_DISH", name: "Rain Dish" },
  { constant: "ABILITY_SAND_STREAM", name: "Sand Stream" },
  { constant: "ABILITY_PRESSURE", name: "Pressure" },
  { constant: "ABILITY_THICK_FAT", name: "Thick Fat" },
  { constant: "ABILITY_EARLY_BIRD", name: "Early Bird" },
  { constant: "ABILITY_FLAME_BODY", name: "Flame Body" },
  { constant: "ABILITY_RUN_AWAY", name: "Run Away" },
  { constant: "ABILITY_KEEN_EYE", name: "Keen Eye" },
  { constant: "ABILITY_HYPER_CUTTER", name: "Hyper Cutter" },
  { constant: "ABILITY_PICKUP", name: "Pickup" },
  { constant: "ABILITY_TRUANT", name: "Truant" },
  { constant: "ABILITY_HUSTLE", name: "Hustle" },
  { constant: "ABILITY_CUTE_CHARM", name: "Cute Charm" },
  { constant: "ABILITY_PLUS", name: "Plus" },
  { constant: "ABILITY_MINUS", name: "Minus" },
  { constant: "ABILITY_NATURAL_CURE", name: "Natural Cure" },
  { constant: "ABILITY_FORECAST", name: "Forecast" },
  { constant: "ABILITY_STICKY_HOLD", name: "Sticky Hold" },
  { constant: "ABILITY_SHED_SKIN", name: "Shed Skin" },
  { constant: "ABILITY_GUTS", name: "Guts" },
  { constant: "ABILITY_MARVEL_SCALE", name: "Marvel Scale" },
  { constant: "ABILITY_LIQUID_OOZE", name: "Liquid Ooze" },
  { constant: "ABILITY_OVERGROW", name: "Overgrow" },
  { constant: "ABILITY_BLAZE", name: "Blaze" },
  { constant: "ABILITY_TORRENT", name: "Torrent" },
  { constant: "ABILITY_SWARM", name: "Swarm" },
  { constant: "ABILITY_ROCK_HEAD", name: "Rock Head" },
  { constant: "ABILITY_DROUGHT", name: "Drought" },
  { constant: "ABILITY_ARENA_TRAP", name: "Arena Trap" },
  { constant: "ABILITY_VITAL_SPIRIT", name: "Vital Spirit" },
  { constant: "ABILITY_WHITE_SMOKE", name: "White Smoke" },
  { constant: "ABILITY_PURE_POWER", name: "Pure Power" },
  { constant: "ABILITY_SHELL_ARMOR", name: "Shell Armor" },
  { constant: "ABILITY_AIR_LOCK", name: "Air Lock" },
  { constant: "ABILITY_TANGLED_FEET", name: "Tangled Feet" },
  { constant: "ABILITY_MOTOR_DRIVE", name: "Motor Drive" },
  { constant: "ABILITY_RIVALRY", name: "Rivalry" },
  { constant: "ABILITY_STEADFAST", name: "Steadfast" },
  { constant: "ABILITY_SNOW_CLOAK", name: "Snow Cloak" },
  { constant: "ABILITY_GLUTTONY", name: "Gluttony" },
  { constant: "ABILITY_ANGER_POINT", name: "Anger Point" },
  { constant: "ABILITY_UNBURDEN", name: "Unburden" },
  { constant: "ABILITY_HEATPROOF", name: "Heatproof" },
  { constant: "ABILITY_SIMPLE", name: "Simple" },
  { constant: "ABILITY_DRY_SKIN", name: "Dry Skin" },
  { constant: "ABILITY_DOWNLOAD", name: "Download" },
  { constant: "ABILITY_IRON_FIST", name: "Iron Fist" },
  { constant: "ABILITY_POISON_HEAL", name: "Poison Heal" },
  { constant: "ABILITY_ADAPTABILITY", name: "Adaptability" },
  { constant: "ABILITY_SKILL_LINK", name: "Skill Link" },
  { constant: "ABILITY_HYDRATION", name: "Hydration" },
  { constant: "ABILITY_SOLAR_POWER", name: "Solar Power" },
  { constant: "ABILITY_QUICK_FEET", name: "Quick Feet" },
  { constant: "ABILITY_NORMALIZE", name: "Normalize" },
  { constant: "ABILITY_SNIPER", name: "Sniper" },
  { constant: "ABILITY_MAGIC_GUARD", name: "Magic Guard" },
  { constant: "ABILITY_NO_GUARD", name: "No Guard" },
  { constant: "ABILITY_STALL", name: "Stall" },
  { constant: "ABILITY_TECHNICIAN", name: "Technician" },
  { constant: "ABILITY_LEAF_GUARD", name: "Leaf Guard" },
  { constant: "ABILITY_KLUTZ", name: "Klutz" },
  { constant: "ABILITY_MOLD_BREAKER", name: "Mold Breaker" },
  { constant: "ABILITY_SUPER_LUCK", name: "Super Luck" },
  { constant: "ABILITY_AFTERMATH", name: "Aftermath" },
  { constant: "ABILITY_ANTICIPATION", name: "Anticipation" },
  { constant: "ABILITY_FOREWARN", name: "Forewarn" },
  { constant: "ABILITY_UNAWARE", name: "Unaware" },
  { constant: "ABILITY_TINTED_LENS", name: "Tinted Lens" },
  { constant: "ABILITY_FILTER", name: "Filter" },
  { constant: "ABILITY_SLOW_START", name: "Slow Start" },
  { constant: "ABILITY_SCRAPPY", name: "Scrappy" },
  { constant: "ABILITY_STORM_DRAIN", name: "Storm Drain" },
  { constant: "ABILITY_ICE_BODY", name: "Ice Body" },
  { constant: "ABILITY_FORECAST", name: "Forecast" },
  { constant: "ABILITY_THICK_FAT", name: "Thick Fat" },
  { constant: "ABILITY_FLOWER_GIFT", name: "Flower Gift" },
  { constant: "ABILITY_BAD_DREAMS", name: "Bad Dreams" },
  { constant: "ABILITY_PICKPOCKET", name: "Pickpocket" },
  { constant: "ABILITY_SHEER_FORCE", name: "Sheer Force" },
  { constant: "ABILITY_CONTRARY", name: "Contrary" },
  { constant: "ABILITY_UNNERVE", name: "Unnerve" },
  { constant: "ABILITY_DEFIANT", name: "Defiant" },
  { constant: "ABILITY_DEFEATIST", name: "Defeatist" },
  { constant: "ABILITY_CURSED_BODY", name: "Cursed Body" },
  { constant: "ABILITY_HEALER", name: "Healer" },
  { constant: "ABILITY_FRIEND_GUARD", name: "Friend Guard" },
  { constant: "ABILITY_WEAK_ARMOR", name: "Weak Armor" },
  { constant: "ABILITY_HEAVY_METAL", name: "Heavy Metal" },
  { constant: "ABILITY_LIGHT_METAL", name: "Light Metal" },
  { constant: "ABILITY_MULTISCALE", name: "Multiscale" },
  { constant: "ABILITY_TOXIC_BOOST", name: "Toxic Boost" },
  { constant: "ABILITY_FLARE_BOOST", name: "Flare Boost" },
  { constant: "ABILITY_HARVEST", name: "Harvest" },
  { constant: "ABILITY_TELEPATHY", name: "Telepathy" },
  { constant: "ABILITY_MOXIE", name: "Moxie" },
  { constant: "ABILITY_JUSTIFIED", name: "Justified" },
  { constant: "ABILITY_RATTLED", name: "Rattled" },
  { constant: "ABILITY_MAGIC_BOUNCE", name: "Magic Bounce" },
  { constant: "ABILITY_SAP_SIPPER", name: "Sap Sipper" },
  { constant: "ABILITY_PRANKSTER", name: "Prankster" },
  { constant: "ABILITY_SAND_FORCE", name: "Sand Force" },
  { constant: "ABILITY_IRON_BARBS", name: "Iron Barbs" },
  { constant: "ABILITY_ZEN_MODE", name: "Zen Mode" },
  { constant: "ABILITY_VICTORY_STAR", name: "Victory Star" },
  { constant: "ABILITY_TURBOBLAZE", name: "Turboblaze" },
  { constant: "ABILITY_TERAVOLT", name: "Teravolt" },
  { constant: "ABILITY_AROMA_VEIL", name: "Aroma Veil" },
  { constant: "ABILITY_FLOWER_VEIL", name: "Flower Veil" },
  { constant: "ABILITY_CHEEK_POUCH", name: "Cheek Pouch" },
  { constant: "ABILITY_PROTEAN", name: "Protean" },
  { constant: "ABILITY_FUR_COAT", name: "Fur Coat" },
  { constant: "ABILITY_MAGICIAN", name: "Magician" },
  { constant: "ABILITY_BULLETPROOF", name: "Bulletproof" },
  { constant: "ABILITY_COMPETITIVE", name: "Competitive" },
  { constant: "ABILITY_STRONG_JAW", name: "Strong Jaw" },
  { constant: "ABILITY_REFRIGERATE", name: "Refrigerate" },
  { constant: "ABILITY_SWEET_VEIL", name: "Sweet Veil" },
  { constant: "ABILITY_STANCE_CHANGE", name: "Stance Change" },
  { constant: "ABILITY_GALE_WINGS", name: "Gale Wings" },
  { constant: "ABILITY_MEGA_LAUNCHER", name: "Mega Launcher" },
  { constant: "ABILITY_GRASS_PELT", name: "Grass Pelt" },
  { constant: "ABILITY_SYMBIOSIS", name: "Symbiosis" },
  { constant: "ABILITY_TOUGH_CLAWS", name: "Tough Claws" },
  { constant: "ABILITY_PIXILATE", name: "Pixilate" },
  { constant: "ABILITY_GOOEY", name: "Gooey" },
  { constant: "ABILITY_AERILATE", name: "Aerilate" },
  { constant: "ABILITY_PARENTAL_BOND", name: "Parental Bond" },
  { constant: "ABILITY_DARK_AURA", name: "Dark Aura" },
  { constant: "ABILITY_FAIRY_AURA", name: "Fairy Aura" },
  { constant: "ABILITY_AURA_BREAK", name: "Aura Break" },
  { constant: "ABILITY_PRIMORDIAL_SEA", name: "Primordial Sea" },
  { constant: "ABILITY_DESOLATE_LAND", name: "Desolate Land" },
  { constant: "ABILITY_DELTA_STREAM", name: "Delta Stream" },
  { constant: "ABILITY_STAMINA", name: "Stamina" },
  { constant: "ABILITY_WIMP_OUT", name: "Wimp Out" },
  { constant: "ABILITY_EMERGENCY_EXIT", name: "Emergency Exit" },
  { constant: "ABILITY_WATER_COMPACTION", name: "Water Compaction" },
  { constant: "ABILITY_MERCILESS", name: "Merciless" },
  { constant: "ABILITY_SHIELDS_DOWN", name: "Shields Down" },
  { constant: "ABILITY_STAKEOUT", name: "Stakeout" },
  { constant: "ABILITY_WATER_BUBBLE", name: "Water Bubble" },
  { constant: "ABILITY_STEELWORKER", name: "Steelworker" },
  { constant: "ABILITY_BERSERK", name: "Berserk" },
  { constant: "ABILITY_SLUSH_RUSH", name: "Slush Rush" },
  { constant: "ABILITY_LONG_REACH", name: "Long Reach" },
  { constant: "ABILITY_LIQUID_VOICE", name: "Liquid Voice" },
  { constant: "ABILITY_TRIAGE", name: "Triage" },
  { constant: "ABILITY_GALVANIZE", name: "Galvanize" },
  { constant: "ABILITY_SURGE_SURFER", name: "Surge Surfer" },
  { constant: "ABILITY_SCHOOLING", name: "Schooling" },
  { constant: "ABILITY_DISGUISE", name: "Disguise" },
  { constant: "ABILITY_BATTLE_BOND", name: "Battle Bond" },
  { constant: "ABILITY_POWER_CONSTRUCT", name: "Power Construct" },
  { constant: "ABILITY_CORROSION", name: "Corrosion" },
  { constant: "ABILITY_COMATOSE", name: "Comatose" },
  { constant: "ABILITY_QUEENLY_MAJESTY", name: "Queenly Majesty" },
  { constant: "ABILITY_INNARDS_OUT", name: "Innards Out" },
  { constant: "ABILITY_DANCER", name: "Dancer" },
  { constant: "ABILITY_BATTERY", name: "Battery" },
  { constant: "ABILITY_RKS_SYSTEM", name: "RKS System" },
  { constant: "ABILITY_ELECTRIC_SURGE", name: "Electric Surge" },
  { constant: "ABILITY_PSYCHIC_SURGE", name: "Psychic Surge" },
  { constant: "ABILITY_MISTY_SURGE", name: "Misty Surge" },
  { constant: "ABILITY_GRASSY_SURGE", name: "Grassy Surge" },
  { constant: "ABILITY_FULL_METAL_BODY", name: "Full Metal Body" },
  { constant: "ABILITY_SHADOW_SHIELD", name: "Shadow Shield" },
  { constant: "ABILITY_PRISM_ARMOR", name: "Prism Armor" },
  { constant: "ABILITY_NEUROFORCE", name: "Neuroforce" },
  { constant: "ABILITY_INTREPID_SWORD", name: "Intrepid Sword" },
  { constant: "ABILITY_DAUNTLESS_SHIELD", name: "Dauntless Shield" },
  { constant: "ABILITY_LIBERO", name: "Libero" },
  { constant: "ABILITY_BALL_FETCH", name: "Ball Fetch" },
  { constant: "ABILITY_COTTON_DOWN", name: "Cotton Down" },
  { constant: "ABILITY_PROPELLER_TAIL", name: "Propeller Tail" },
  { constant: "ABILITY_MIRROR_ARMOR", name: "Mirror Armor" },
  { constant: "ABILITY_GULP_MISSILE", name: "Gulp Missile" },
  { constant: "ABILITY_STALWART", name: "Stalwart" },
  { constant: "ABILITY_STEAM_ENGINE", name: "Steam Engine" },
  { constant: "ABILITY_PUNK_ROCK", name: "Punk Rock" },
  { constant: "ABILITY_SAND_SPIT", name: "Sand Spit" },
  { constant: "ABILITY_ICE_SCALES", name: "Ice Scales" },
  { constant: "ABILITY_RIPEN", name: "Ripen" },
  { constant: "ABILITY_PASTEL_VEIL", name: "Pastel Veil" },
  { constant: "ABILITY_HUNGER_SWITCH", name: "Hunger Switch" },
  { constant: "ABILITY_QUICK_DRAW", name: "Quick Draw" },
  { constant: "ABILITY_UNSEEN_FIST", name: "Unseen Fist" },
  { constant: "ABILITY_CURIOUS_MEDICINE", name: "Curious Medicine" },
  { constant: "ABILITY_TRANSISTOR", name: "Transistor" },
  { constant: "ABILITY_DRAGS_MAUL", name: "Dragon's Maw" },
  { constant: "ABILITY_CHILLING_NEIGH", name: "Chilling Neigh" },
  { constant: "ABILITY_GRIM_NEIGH", name: "Grim Neigh" },
  { constant: "ABILITY_AS_ONE_ICE_RIDER", name: "As One (Ice Rider)" },
  { constant: "ABILITY_AS_ONE_SHADOW_RIDER", name: "As One (Shadow Rider)" },
  { constant: "ABILITY_LINGERING_AROMA", name: "Lingering Aroma" },
  { constant: "ABILITY_SEED_SOWER", name: "Seed Sower" },
  { constant: "ABILITY_THERMAL_EXCHANGE", name: "Thermal Exchange" },
  { constant: "ABILITY_ANGER_SHELL", name: "Anger Shell" },
  { constant: "ABILITY_PURIFYING_SALT", name: "Purifying Salt" },
  { constant: "ABILITY_WELL_BAKED_BODY", name: "Well-Baked Body" },
  { constant: "ABILITY_WIND_RIDER", name: "Wind Rider" },
  { constant: "ABILITY_GUARD_DOG", name: "Guard Dog" },
  { constant: "ABILITY_ROCKY_PAYLOAD", name: "Rocky Payload" },
  { constant: "ABILITY_WIND_RIDER", name: "Wind Rider" },
  { constant: "ABILITY_ZERO_TO_HERO", name: "Zero to Hero" },
  { constant: "ABILITY_COMMANDER", name: "Commander" },
  { constant: "ABILITY_ELECTROMORPHOSIS", name: "Electromorphosis" },
  { constant: "ABILITY_SUPERSWEET_SYRUP", name: "Supersweet Syrup" },
  { constant: "ABILITY_HOSPITALITY", name: "Hospitality" },
  { constant: "ABILITY_TOXIC_CHAIN", name: "Toxic Chain" },
  { constant: "ABILITY_ARMOR_TAIL", name: "Armor Tail" },
  { constant: "ABILITY_EARTH_EATER", name: "Earth Eater" },
  { constant: "ABILITY_MYCELIUM_MIGHT", name: "Mycelium Might" },
  { constant: "ABILITY_MIGHTY_MENU", name: "Mighty Menu" },
  { constant: "ABILITY_COSTAR", name: "Costar" },
  { constant: "ABILITY_TOXIC_DEBRIS", name: "Toxic Debris" },
  { constant: "ABILITY_SUPREME_OVERLORD", name: "Supreme Overlord" },
  { constant: "ABILITY_CUD_CHEW", name: "Cud Chew" },
  { constant: "ABILITY_SHARPNESS", name: "Sharpness" },
  { constant: "ABILITY_GUARDIAN_OF_ALOLA", name: "Guardian of Alola" },
  { constant: "ABILITY_URSINE_FURY", name: "Ursine Fury" },
  { constant: "ABILITY_HOSPITALITY", name: "Hospitality" },
];

// ---------------------------------------------------------------------------
// Move effects (battle_move_effects.h — common subset)
// ---------------------------------------------------------------------------
export const MOVE_EFFECTS: { constant: string; name: string }[] = [
  { constant: "EFFECT_HIT", name: "Hit" },
  { constant: "EFFECT_SLEEP", name: "Sleep" },
  { constant: "EFFECT_POISON_HIT", name: "Poison Hit" },
  { constant: "EFFECT_ABSORB", name: "Absorb" },
  { constant: "EFFECT_BURN_HIT", name: "Burn Hit" },
  { constant: "EFFECT_FREEZE_HIT", name: "Freeze Hit" },
  { constant: "EFFECT_PARALYZE_HIT", name: "Paralyze Hit" },
  { constant: "EFFECT_EXPLOSION", name: "Explosion" },
  { constant: "EFFECT_DREAM_EATER", name: "Dream Eater" },
  { constant: "EFFECT_MIRROR_MOVE", name: "Mirror Move" },
  { constant: "EFFECT_ATTACK_UP", name: "Attack Up" },
  { constant: "EFFECT_DEFENSE_UP", name: "Defense Up" },
  { constant: "EFFECT_SPEED_UP", name: "Speed Up" },
  { constant: "EFFECT_SP_ATK_UP", name: "Sp. Atk Up" },
  { constant: "EFFECT_SP_DEF_UP", name: "Sp. Def Up" },
  { constant: "EFFECT_ACCURACY_UP", name: "Accuracy Up" },
  { constant: "EFFECT_EVASION_UP", name: "Evasion Up" },
  { constant: "EFFECT_ATTACK_DOWN", name: "Attack Down" },
  { constant: "EFFECT_DEFENSE_DOWN", name: "Defense Down" },
  { constant: "EFFECT_SPEED_DOWN", name: "Speed Down" },
  { constant: "EFFECT_SP_ATK_DOWN", name: "Sp. Atk Down" },
  { constant: "EFFECT_SP_DEF_DOWN", name: "Sp. Def Down" },
  { constant: "EFFECT_ACCURACY_DOWN", name: "Accuracy Down" },
  { constant: "EFFECT_EVASION_DOWN", name: "Evasion Down" },
  { constant: "EFFECT_RECHARGE", name: "Recharge" },
  { constant: "EFFECT_COUNTER", name: "Counter" },
  { constant: "EFFECT_OHKO", name: "OHKO" },
  { constant: "EFFECT_FURY_CUTTER", name: "Fury Cutter" },
  { constant: "EFFECT_SUPER_FANG", name: "Super Fang" },
  { constant: "EFFECT_RECOIL", name: "Recoil" },
  { constant: "EFFECT_CONFUSE_HIT", name: "Confuse Hit" },
  { constant: "EFFECT_TWO_TURNS_ATTACK", name: "Two-Turn Attack" },
  { constant: "EFFECT_FLINCH_HIT", name: "Flinch Hit" },
  { constant: "EFFECT_RESTORE_HP", name: "Restore HP" },
  { constant: "EFFECT_STATUS2", name: "Status 2" },
  { constant: "EFFECT_PAY_DAY", name: "Pay Day" },
  { constant: "EFFECT_BIDE", name: "Bide" },
  { constant: "EFFECT_RAMPAGE", name: "Rampage" },
  { constant: "EFFECT_ROAR", name: "Roar" },
  { constant: "EFFECT_MULTI_HIT", name: "Multi Hit" },
  { constant: "EFFECT_CONVERSION", name: "Conversion" },
  { constant: "EFFECT_FLAME_WHEEL", name: "Flame Wheel" },
  { constant: "EFFECT_THRASH", name: "Thrash" },
  { constant: "EFFECT_KNOCK_OFF", name: "Knock Off" },
  { constant: "EFFECT_PRIORITY", name: "Priority" },
  { constant: "EFFECT_STEALTH_ROCK", name: "Stealth Rock" },
  { constant: "EFFECT_SPIKES", name: "Spikes" },
  { constant: "EFFECT_TOXIC_SPIKES", name: "Toxic Spikes" },
  { constant: "EFFECT_STICKY_WEB", name: "Sticky Web" },
  { constant: "EFFECT_TRICK_ROOM", name: "Trick Room" },
  { constant: "EFFECT_TAILWIND", name: "Tailwind" },
  { constant: "EFFECT_REFLECT", name: "Reflect" },
  { constant: "EFFECT_LIGHT_SCREEN", name: "Light Screen" },
  { constant: "EFFECT_AURORA_VEIL", name: "Aurora Veil" },
  { constant: "EFFECT_SAFEGUARD", name: "Safeguard" },
  { constant: "EFFECT_MIST", name: "Mist" },
  { constant: "EFFECT_HEAL_BLOCK", name: "Heal Block" },
  { constant: "EFFECT_EMBARGO", name: "Embargo" },
  { constant: "EFFECT_TAUNT", name: "Taunt" },
  { constant: "EFFECT_ENCORE", name: "Encore" },
  { constant: "EFFECT_TORMENT", name: "Torment" },
  { constant: "EFFECT_GRAVITY", name: "Gravity" },
  { constant: "EFFECT_MAGNET_RISE", name: "Magnet Rise" },
  { constant: "EFFECT_AQUA_RING", name: "Aqua Ring" },
  { constant: "EFFECT_SUBSTITUTE", name: "Substitute" },
  { constant: "EFFECT_PROTECT", name: "Protect" },
  { constant: "EFFECT_HEALING_WISH", name: "Healing Wish" },
  { constant: "EFFECT_LUNAR_DANCE", name: "Lunar Dance" },
  { constant: "EFFECT_DEFOG", name: "Defog" },
  { constant: "EFFECT_HAZE", name: "Haze" },
  { constant: "EFFECT_CLEAR_SMOG", name: "Clear Smog" },
  { constant: "EFFECT_DESTINY_BOND", name: "Destiny Bond" },
  { constant: "EFFECT_CURSE", name: "Curse" },
  { constant: "EFFECT_BATON_PASS", name: "Baton Pass" },
  { constant: "EFFECT_PARTING_SHOT", name: "Parting Shot" },
  { constant: "EFFECT_VOLT_SWITCH", name: "Volt Switch" },
  { constant: "EFFECT_U_TURN", name: "U-Turn" },
  { constant: "EFFECT_FLING", name: "Fling" },
  { constant: "EFFECT_NATURE_POWER", name: "Nature Power" },
  { constant: "EFFECT_ROUND", name: "Round" },
  { constant: "EFFECT_ECHOED_VOICE", name: "Echoed Voice" },
  { constant: "EFFECT_ELECTRO_BALL", name: "Electro Ball" },
  { constant: "EFFECT_GYRO_BALL", name: "Gyro Ball" },
  { constant: "EFFECT_PSYSHOCK", name: "Psyshock" },
  { constant: "EFFECT_FOUL_PLAY", name: "Foul Play" },
  { constant: "EFFECT_BODY_PRESS", name: "Body Press" },
  { constant: "EFFECT_POLLEN_PUFF", name: "Pollen Puff" },
  { constant: "EFFECT_PURE_POWER", name: "Pure Power" },
  { constant: "EFFECT_TERA_BLAST", name: "Tera Blast" },
  { constant: "EFFECT_RAGE_FIST", name: "Rage Fist" },
  { constant: "EFFECT_LAST_RESPECTS", name: "Last Respects" },
  { constant: "EFFECT_COMEUPPANCE", name: "Comeuppance" },
  { constant: "EFFECT_SHED_TAIL", name: "Shed Tail" },
  { constant: "EFFECT_CHILLY_RECEPTION", name: "Chilly Reception" },
  { constant: "EFFECT_SALT_CURE", name: "Salt Cure" },
  { constant: "EFFECT_GLAIVE_RUSH", name: "Glaive Rush" },
  { constant: "EFFECT_AXE_KICK", name: "Axe Kick" },
  { constant: "EFFECT_MAKE_IT_RAIN", name: "Make It Rain" },
  { constant: "EFFECT_RUINATION", name: "Ruination" },
  { constant: "EFFECT_FICKLE_BEAM", name: "Fickle Beam" },
  { constant: "EFFECT_BLOOD_MOON", name: "Blood Moon" },
];

// ---------------------------------------------------------------------------
// Move categories
// ---------------------------------------------------------------------------
export const MOVE_CATEGORIES = [
  { constant: "CATEGORY_PHYSICAL", name: "Physical" },
  { constant: "CATEGORY_SPECIAL", name: "Special" },
  { constant: "CATEGORY_STATUS", name: "Status" },
];

// ---------------------------------------------------------------------------
// Move targets
// ---------------------------------------------------------------------------
export const MOVE_TARGETS = [
  { constant: "MOVE_TARGET_SELECTED", name: "Selected" },
  { constant: "MOVE_TARGET_DEPENDS", name: "Depends" },
  { constant: "MOVE_TARGET_RANDOM", name: "Random" },
  { constant: "MOVE_TARGET_BOTH", name: "Both Opponents" },
  { constant: "MOVE_TARGET_USER", name: "User" },
  { constant: "MOVE_TARGET_FOES_AND_ALLY", name: "Foes & Ally" },
  { constant: "MOVE_TARGET_OPPONENTS_FIELD", name: "Opponent's Field" },
  { constant: "MOVE_TARGET_USER_OR_ALLY", name: "User or Ally" },
  { constant: "MOVE_TARGET_ALLY", name: "Ally" },
  { constant: "MOVE_TARGET_ALL_BATTLERS", name: "All Battlers" },
  { constant: "MOVE_TARGET_ALL", name: "Everyone" },
];

// ---------------------------------------------------------------------------
// Move flags
// ---------------------------------------------------------------------------
export const MOVE_FLAGS = [
  { constant: "MOVE_FLAG_MAKES_CONTACT", name: "Makes Contact" },
  { constant: "MOVE_FLAG_PROTECT_AFFECTED", name: "Affected by Protect" },
  { constant: "MOVE_FLAG_MAGIC_COAT_AFFECTED", name: "Magic Coat Affected" },
  { constant: "MOVE_FLAG_SNATCH_AFFECTED", name: "Snatch Affected" },
  { constant: "MOVE_FLAG_MIRROR_MOVE_AFFECTED", name: "Mirror Move Affected" },
  { constant: "MOVE_FLAG_KINGS_ROCK_AFFECTED", name: "King's Rock Affected" },
  { constant: "MOVE_FLAG_HIGH_CRIT", name: "High Crit" },
  { constant: "MOVE_FLAG_HP_RECOVERY", name: "HP Recovery" },
  { constant: "MOVE_FLAG_DANCE", name: "Dance" },
  { constant: "MOVE_FLAG_ATTACKING_STAT_AFFECTED", name: "Stat Affected by Atk" },
  { constant: "MOVE_FLAG_BYPASSES_SUBSTITUTE", name: "Bypasses Substitute" },
  { constant: "MOVE_FLAG_RECHARGE", name: "Recharge" },
  { constant: "MOVE_FLAG_TWO_TURN_MOVE", name: "Two-Turn Move" },
  { constant: "MOVE_FLAG_TRIES_TO_FROZEN_TARGET", name: "Hits Frozen Target" },
  { constant: "MOVE_FLAG_WILL_FAIL_WITH_NO_TARGET", name: "Fails No Target" },
  { constant: "MOVE_FLAG_KEEP_FRESH_MOVES", name: "Keep Fresh Moves" },
  { constant: "MOVE_FLAG_BYPASSES_PROTECT", name: "Bypasses Protect" },
  { constant: "MOVE_FLAG_CANNOT_USE_MOVE", name: "Cannot Use Move" },
  { constant: "MOVE_FLAG_COUNTER_ON_HIT", name: "Counter on Hit" },
  { constant: "MOVE_FLAG_NEEDS_MOVE_TARGET", name: "Needs Move Target" },
  { constant: "MOVE_FLAG_SUCKER_PUNCH", name: "Sucker Punch" },
  { constant: "MOVE_FLAG_TRIAGE_MOVE", name: "Triage Move" },
  { constant: "MOVE_FLAG_CANNOT_USE_IF_ASLEEP", name: "Cannot Use If Asleep" },
  { constant: "MOVE_FLAG_CANNOT_USE_IF_FROZEN", name: "Cannot Use If Frozen" },
  { constant: "MOVE_FLAG_BYPASSES_SAFEGUARD", name: "Bypasses Safeguard" },
  { constant: "MOVE_FLAG_BYPASSES_MAGIC_BOUNCE", name: "Bypasses Magic Bounce" },
];

// ---------------------------------------------------------------------------
// Evolution methods
// ---------------------------------------------------------------------------
export const EVO_METHODS = [
  { constant: "EVO_NONE", name: "None" },
  { constant: "EVO_LEVEL", name: "By Level" },
  { constant: "EVO_ITEM", name: "By Item" },
  { constant: "EVO_TRADE", name: "By Trade" },
  { constant: "EVO_FRIENDSHIP", name: "By Friendship" },
  { constant: "EVO_FRIENDSHIP_DAY", name: "By Friendship (Day)" },
  { constant: "EVO_FRIENDSHIP_NIGHT", name: "By Friendship (Night)" },
  { constant: "EVO_LEVEL_MALE", name: "By Level (Male)" },
  { constant: "EVO_LEVEL_FEMALE", name: "By Level (Female)" },
  { constant: "EVO_ITEM_HOLD_DAY", name: "Hold Item (Day)" },
  { constant: "EVO_ITEM_HOLD_NIGHT", name: "Hold Item (Night)" },
  { constant: "EVO_MOVE", name: "Knows Move" },
  { constant: "EVO_LOCATION", name: "By Location" },
  { constant: "EVO_SPECIFIC_MON_IN_PARTY", name: "Mon in Party" },
  { constant: "EVO_LEVEL_DARK_TYPE_IN_PARTY", name: "Level + Dark in Party" },
  { constant: "EVO_GAME_TARGET", name: "Game Target" },
  { constant: "EVO_CRIT_HIT", name: "Crit Hit 3×" },
  { constant: "EVO_USE_MOVE", name: "Use Move 20×" },
  { constant: "EVO_RECOIL_DAMAGE", name: "Recoil Damage" },
  { constant: "EVO_USE_ITEM", name: "Use Item" },
  { constant: "EVO_DAYCARE", name: "Daycare Level" },
  { constant: "EVO_MEGA_EVOLUTION", name: "Mega Evolution" },
  { constant: "EVO_GIGANTAMAX", name: "Gigantamax" },
  { constant: "EVO_PRIMAL_REVERSION", name: "Primal Reversion" },
  { constant: "EVO_MOVE_TWO_HEARTS", name: "Move Two Hearts" },
  { constant: "EVO_SCRIPT", name: "Script" },
];

// ---------------------------------------------------------------------------
// Front / back animation IDs (subset)
// ---------------------------------------------------------------------------
export const FRONT_ANIM_IDS = [
  "ANIM_V_JOLT",
  "ANIM_V_SHAKE",
  "ANIM_V_SLIDE_WOBBLE",
  "ANIM_V_SLIDE_HORIZONTAL",
  "ANIM_V_TWIST",
  "ANIM_V_STRETCH_VERTICAL",
  "ANIM_V_STRETCH_HORIZONTAL",
  "ANIM_V_FLASH",
  "ANIM_V_SING",
  "ANIM_V_NONE",
];

export const BACK_ANIM_IDS = [
  "BACK_ANIM_NONE",
  "BACK_ANIM_H_SLIDE",
  "BACK_ANIM_H_SLIDE_WOBBLE",
  "BACK_ANIM_H_VIBRATE",
  "BACK_ANIM_H_DIP",
  "BACK_ANIM_V_STRETCH",
  "BACK_ANIM_V_SHRINK",
  "BACK_ANIM_CONCAVE_ARC_SMALL",
  "BACK_ANIM_CONCAVE_ARC_LARGE",
  "BACK_ANIM_CONVEX_ARC_SMALL",
  "BACK_ANIM_CONVEX_ARC_LARGE",
];

// ---------------------------------------------------------------------------
// Cry IDs (subset — expansion uses cry_ids.h)
// ---------------------------------------------------------------------------
export const CRY_IDS = [
  "CRY_BULBASAUR",
  "CRY_IVYSAUR",
  "CRY_VENUSAUR",
  "CRY_CHARMANDER",
  "CRY_CHARMELEON",
  "CRY_CHARIZARD",
  "CRY_SQUIRTLE",
  "CRY_WARTORTLE",
  "CRY_BLASTOISE",
  "CRY_CATERPIE",
  "CRY_METAPOD",
  "CRY_BUTTERFREE",
  "CRY_PIKACHU",
  "CRY_RAICHU",
  "CRY_EEVEE",
  "CRY_SNORLAX",
  "CRY_MEWTWO",
  "CRY_MEW",
  "CRY_RAYQUAZA",
  "CRY_NONE",
];

// ---------------------------------------------------------------------------
// Item pockets & effects (subset)
// ---------------------------------------------------------------------------
export const ITEM_POCKETS = [
  { constant: "POCKET_ITEMS", name: "Items" },
  { constant: "POCKET_BALLS", name: "Poké Balls" },
  { constant: "POCKET_TM_HM", name: "TMs/HMs" },
  { constant: "POCKET_BERRIES", name: "Berries" },
  { constant: "POCKET_KEY_ITEMS", name: "Key Items" },
  { constant: "POCKET_MAIL", name: "Mail" },
  { constant: "POCKET_BATTLE_ITEMS", name: "Battle Items" },
  { constant: "POCKET_FUEL", name: "Fuel" },
];

export const ITEM_EFFECTS = [
  "ITEM_EFFECT_NONE",
  "ITEM_EFFECT_POKEBALL",
  "ITEM_EFFECT_RESTORE_HP",
  "ITEM_EFFECT_CURE_STATUS",
  "ITEM_EFFECT_EVOLUTION",
  "ITEM_EFFECT_TM",
  "ITEM_EFFECT_HOLD",
  "ITEM_EFFECT_BERRY",
  "ITEM_EFFECT_KEY",
  "ITEM_EFFECT_FORM_CHANGE",
];

export const HOLD_EFFECTS = [
  "HOLD_EFFECT_NONE",
  "HOLD_EFFECT_RESTORE_HP",
  "HOLD_EFFECT_CURE_STATUS",
  "HOLD_EFFECT_BOOST_STAT",
  "HOLD_EFFECT_TYPE_BOOST",
  "HOLD_EFFECT_EXP_BOOST",
  "HOLD_EFFECT_LEFTOVERS",
  "HOLD_EFFECT_FLINCH",
  "HOLD_EFFECT_PROTECT",
  "HOLD_EFFECT_MEGA_STONE",
  "HOLD_EFFECT_Z_CRYSTAL",
  "HOLD_EFFECT_TERA_ORB",
];

export const ITEM_CATEGORIES = [
  "ITEM_CATEGORY_ITEMS",
  "ITEM_CATEGORY_POKEBALLS",
  "ITEM_CATEGORY_TMS",
  "ITEM_CATEGORY_HMS",
  "ITEM_CATEGORY_BERRIES",
  "ITEM_CATEGORY_KEY_ITEMS",
  "ITEM_CATEGORY_FORM_CHANGE",
  "ITEM_CATEGORY_MEGA_STONES",
  "ITEMCATEGORY_Z_CRYSTALS",
];

// ---------------------------------------------------------------------------
// Gender ratio helpers
// ---------------------------------------------------------------------------
export const GENDER_RATIOS = [
  { constant: 0, name: "100% Male (0)" },
  { constant: 31, name: "87.5% Male" },
  { constant: 63, name: "75% Male" },
  { constant: 89, name: "65% Male" },
  { constant: 127, name: "50% / 50%" },
  { constant: 165, name: "35% Male" },
  { constant: 191, name: "25% Male" },
  { constant: 223, name: "12.5% Male" },
  { constant: 254, name: "100% Female" },
  { constant: 255, name: "Genderless" },
];

// ---------------------------------------------------------------------------
// Species flags
// ---------------------------------------------------------------------------
export const SPECIES_FLAGS = [
  { constant: "isMythical", name: "Mythical" },
  { constant: "isSubLegendary", name: "Sub-Legendary" },
  { constant: "isRestrictedLegendary", name: "Restricted Legendary" },
  { constant: "isAlolanForm", name: "Alolan Form" },
  { constant: "isGalarianForm", name: "Galarian Form" },
  { constant: "isHisuianForm", name: "Hisuian Form" },
  { constant: "isPaldeanForm", name: "Paldean Form" },
  { constant: "isUltraBeast", name: "Ultra Beast" },
  { constant: "isParadox", name: "Paradox" },
  { constant: "isMegaEvolution", name: "Mega Evolution" },
  { constant: "isPrimalReversion", name: "Primal Reversion" },
  { constant: "isTotem", name: "Totem" },
  { constant: "isTeraForm", name: "Tera Form" },
  { constant: "isGigantamax", name: "Gigantamax" },
  { constant: "cannotBeTraded", name: "Cannot Be Traded" },
  { constant: "forceChildrenToInheritEmptiness", name: "Force Empty Inherit" },
  { constant: "perfectIVCount", name: "Perfect IV Count" },
  { constant: "genderDifference", name: "Has Gender Difference" },
];

// ---------------------------------------------------------------------------
// Effectiveness multipliers (for type chart)
// ---------------------------------------------------------------------------
export const EFFECTIVENESS_OPTIONS = [
  { value: 0, label: "0× (No effect)" },
  { value: 0.25, label: "0.25×" },
  { value: 0.5, label: "0.5× (Not very effective)" },
  { value: 1, label: "1× (Normal)" },
  { value: 2, label: "2× (Super effective)" },
  { value: 4, label: "4× (Devastating)" },
];

// ---------------------------------------------------------------------------
// Status condition categories
// ---------------------------------------------------------------------------
export const STATUS_CATEGORIES = [
  { constant: "non_volatile", name: "Non-Volatile" },
  { constant: "volatile", name: "Volatile" },
  { constant: "field", name: "Field Condition" },
];

export const BUILTIN_STATUSES = [
  { constant: "STATUS_SLEEP", name: "Sleep" },
  { constant: "STATUS_POISON", name: "Poison" },
  { constant: "STATUS_BURN", name: "Burn" },
  { constant: "STATUS_FREEZE", name: "Freeze" },
  { constant: "STATUS_PARALYSIS", name: "Paralysis" },
  { constant: "STATUS_TOXIC_POISON", name: "Badly Poison (Toxic)" },
  { constant: "STATUS_FROZEN", name: "Frozen" },
];

// ---------------------------------------------------------------------------
// Helper: Pokémon base stat color helper
// ---------------------------------------------------------------------------
export const STAT_META: { key: string; label: string; color: string; max: number }[] = [
  { key: "baseHP", label: "HP", color: "#DF2147", max: 255 },
  { key: "baseAttack", label: "Attack", color: "#EE8130", max: 190 },
  { key: "baseDefense", label: "Defense", color: "#F7D02C", max: 230 },
  { key: "baseSpAttack", label: "Sp. Atk", color: "#6F35FC", max: 194 },
  { key: "baseSpDefense", label: "Sp. Def", color: "#7AC74C", max: 230 },
  { key: "baseSpeed", label: "Speed", color: "#6390F0", max: 180 },
];

// ---------------------------------------------------------------------------
// Type-effectiveness chart (canonical Gen 9, attacker → defender)
// Used to validate custom types and pre-fill type charts
// ---------------------------------------------------------------------------
export const CANONICAL_TYPE_CHART: Record<string, Record<string, number>> = {
  TYPE_NORMAL: { TYPE_ROCK: 0.5, TYPE_GHOST: 0, TYPE_STEEL: 0.5 },
  TYPE_FIGHTING: { TYPE_NORMAL: 2, TYPE_FLYING: 0.5, TYPE_POISON: 0.5, TYPE_ROCK: 2, TYPE_BUG: 0.5, TYPE_GHOST: 0, TYPE_STEEL: 2, TYPE_PSYCHIC: 0.5, TYPE_ICE: 2, TYPE_DARK: 2, TYPE_FAIRY: 0.5 },
  TYPE_FLYING: { TYPE_FIGHTING: 2, TYPE_ROCK: 0.5, TYPE_BUG: 2, TYPE_STEEL: 0.5, TYPE_GRASS: 2, TYPE_ELECTRIC: 0.5 },
  TYPE_POISON: { TYPE_POISON: 0.5, TYPE_GROUND: 0.5, TYPE_ROCK: 0.5, TYPE_GHOST: 0.5, TYPE_STEEL: 0, TYPE_GRASS: 2, TYPE_FAIRY: 2 },
  TYPE_GROUND: { TYPE_FLYING: 0, TYPE_POISON: 2, TYPE_ROCK: 2, TYPE_BUG: 0.5, TYPE_STEEL: 2, TYPE_FIRE: 2, TYPE_GRASS: 0.5, TYPE_ELECTRIC: 2 },
  TYPE_ROCK: { TYPE_FIGHTING: 0.5, TYPE_FLYING: 2, TYPE_GROUND: 0.5, TYPE_BUG: 2, TYPE_STEEL: 0.5, TYPE_FIRE: 2, TYPE_ICE: 2 },
  TYPE_BUG: { TYPE_FIGHTING: 0.5, TYPE_FLYING: 0.5, TYPE_POISON: 0.5, TYPE_GHOST: 0.5, TYPE_STEEL: 0.5, TYPE_FIRE: 0.5, TYPE_GRASS: 2, TYPE_PSYCHIC: 2, TYPE_DARK: 2, TYPE_FAIRY: 0.5 },
  TYPE_GHOST: { TYPE_NORMAL: 0, TYPE_GHOST: 2, TYPE_PSYCHIC: 2, TYPE_DARK: 0.5 },
  TYPE_STEEL: { TYPE_ROCK: 2, TYPE_STEEL: 0.5, TYPE_FIRE: 0.5, TYPE_WATER: 0.5, TYPE_GRASS: 0.5, TYPE_ELECTRIC: 0.5, TYPE_ICE: 2, TYPE_FAIRY: 2 },
  TYPE_FIRE: { TYPE_ROCK: 0.5, TYPE_BUG: 2, TYPE_STEEL: 2, TYPE_FIRE: 0.5, TYPE_WATER: 0.5, TYPE_GRASS: 2, TYPE_ICE: 2 },
  TYPE_WATER: { TYPE_GROUND: 2, TYPE_ROCK: 2, TYPE_WATER: 0.5, TYPE_GRASS: 0.5, TYPE_FIRE: 2 },
  TYPE_GRASS: { TYPE_FLYING: 0.5, TYPE_POISON: 0.5, TYPE_GROUND: 2, TYPE_ROCK: 2, TYPE_BUG: 0.5, TYPE_STEEL: 0.5, TYPE_FIRE: 0.5, TYPE_WATER: 2, TYPE_GRASS: 0.5 },
  TYPE_ELECTRIC: { TYPE_GROUND: 0, TYPE_FLYING: 2, TYPE_GRASS: 0.5, TYPE_ELECTRIC: 0.5, TYPE_WATER: 2 },
  TYPE_PSYCHIC: { TYPE_FIGHTING: 2, TYPE_POISON: 2, TYPE_DARK: 0, TYPE_STEEL: 0.5, TYPE_PSYCHIC: 0.5 },
  TYPE_ICE: { TYPE_FIRE: 0.5, TYPE_WATER: 0.5, TYPE_GRASS: 2, TYPE_ICE: 0.5, TYPE_GROUND: 2, TYPE_FLYING: 2, TYPE_DRAGON: 2, TYPE_STEEL: 0.5 },
  TYPE_DRAGON: { TYPE_STEEL: 0.5, TYPE_FAIRY: 0, TYPE_DRAGON: 2 },
  TYPE_DARK: { TYPE_FIGHTING: 0.5, TYPE_GHOST: 2, TYPE_PSYCHIC: 2, TYPE_DARK: 0.5, TYPE_FAIRY: 0.5 },
  TYPE_FAIRY: { TYPE_POISON: 0.5, TYPE_STEEL: 0.5, TYPE_FIRE: 0.5, TYPE_FIGHTING: 2, TYPE_DRAGON: 2, TYPE_DARK: 2 },
};
